volumes:
  psql_kratos_volume:
  psql_hydra_volume:

networks:
  flyer_network:
    driver: bridge

services:
  # ============================================================
  # AUTH Context
  # ============================================================
  psql_keycloak:
    image: postgres:17-alpine
    container_name: flyer_psql_keycloak
    environment:
      POSTGRES_DB: flyer_db
      POSTGRES_USER: keycloak_username
      POSTGRES_PASSWORD: keycloak_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - flyer_network
    ports:
      - "5432:5433"
    profiles:
      - auth
    
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.5
    container_name: flyer_keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://psql_keycloak:5432/flyer_db
      KC_DB_USERNAME: keycloak_username
      KC_DB_PASSWORD: keycloak_password
    depends_on:
      psql_keycloak:
        condition: service_healthy
    networks:
      - flyer_network
    volumes:
      - ./auth/keycloakify/dist_keycloak:/opt/keycloak/providers/
    ports:
      - "8080:8080"
    command: ["start-dev"]
    profiles:
      - auth

  # ============================================================
  # API Context
  # ============================================================
  psql_api:
    image: postgres:17-alpine
    container_name: flyer_psql_api
    environment:
      POSTGRES_DB: flyer_db
      POSTGRES_USER: api_username
      POSTGRES_PASSWORD: api_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - flyer_network
    ports:
      - "5433:5432"
    profiles:
      - api

  cassandra_api:
    image: cassandra:5.0.6
    container_name: flyer_cassandra_api
    networks:
      - flyer_network
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_DC: flyer_datacenter
      CASSANDRA_CLUSTER_NAME: flyer_cluster
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 10s
      timeout: 5s
      retries: 10
    profiles:
      - api

  cassandra_init:
    image: cassandra:5.0.6
    container_name: flyer_cassandra_init
    networks:
      - flyer_network
    depends_on:
      cassandra_api:
        condition: service_healthy
    volumes:
      - ./api/flyer_api/cassandra_init.cql:/cassandra_init.cql
    command: cqlsh cassandra_api -f /cassandra_init.cql
    profiles:
      - api

  neo4j_api:
    image: neo4j
    container_name: flyer_neo4j_api
    networks:
      - flyer_network
    ports:
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/api_password"
    profiles:
      - api