server:
  port: 8000

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/flyer_db"
    username: "api_username"
    password: "api_password"
  cassandra:
    keyspace-name: "flyer_keyspace"
    contact-points: "localhost:9042"
    local-datacenter: "flyer_datacenter"
  neo4j:
    uri: "bolt://localhost:7687"
    authentication:
      username: "neo4j"
      password: "api_password"
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/flyer